# Generated by Django 3.2.8 on 2021-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
