# Generated by Django 3.2.8 on 2021-11-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
