# Generated by Django 3.2.8 on 2021-11-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Classification', 'Classification'), ('Sizing', 'Sizing'), ('Quotation', 'Quotation'), ('Negotiation', 'Negotiation'), ('Invoiced', 'Invoiced'), ('Paid out', 'Paid out'), ('Closed won', 'Closed won'), ('Closed lost', 'Closed lost')], default='Uncategorized', max_length=20),
        ),
    ]
