# Generated by Django 3.2.8 on 2021-11-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.SlugField(choices=[('uncategorized', 'Uncategorized'), ('classification', 'Classification'), ('sizing', 'Sizing'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('invoiced', 'Invoiced'), ('paid-out', 'Paid out'), ('closed-won', 'Closed won'), ('closed-lost', 'Closed lost')], default='uncategorized', max_length=20),
        ),
    ]
