# Generated by Django 3.2.8 on 2021-11-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Classification', 'Classification'), ('Sizing', 'Sizing'), ('Quotation', 'Quotation'), ('Negotiation', 'Negotiation'), ('Invoiced', 'Invoiced'), ('Paid Out', 'Paid Out'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Uncategorized', max_length=20),
        ),
    ]
