# Generated by Django 3.2.7 on 2021-11-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_alter_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('repeat', models.BooleanField(choices=[(True, 'Repetir'), (False, 'No repetir')], default=False)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('priority', models.CharField(choices=[('Muy alta', 'Muy alta'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Muy baja', 'Muy baja')], default='Media', max_length=10)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
