# Generated by Django 3.2.8 on 2021-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('billing_street', models.CharField(blank=True, max_length=50)),
                ('billing_city', models.CharField(blank=True, max_length=50)),
                ('billing_state', models.CharField(blank=True, max_length=50)),
                ('billing_country', models.CharField(blank=True, max_length=50)),
                ('billing_code', models.CharField(blank=True, max_length=20)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
